name = "TT"
uuid = "b3ec058e-2429-452b-a002-877aa7c4c6fa"
authors = ["Filipe P. Farias"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
